language: python
python:
  - "2.6"
  - "2.7"

env:
#  - DJANGO=django==1.3.7
  - DJANGO=django==1.4.10
  - DJANGO=django==1.5.5
  - DJANGO=django==1.6.2
  - DJANGO=django==1.6.6
  - DJANGO=django==1.7
  - DJANGO=django==1.8
  - DJANGO=django==1.9

install:
  - pip install -q $DJANGO --use-mirrors
#  this test runner is now installed via script if necessary
#  - pip install https://github.com/jorgebastida/django-app-test-runner/zipball/master




branches:
  only:
    - master
    - develop

matrix:
  exclude:
    # Django>1.5 strongly recommends python 2.7 or later (so skip 2.6)
    - python: "2.6"
      env: DJANGO=django==1.5.5
    - python: "2.6"
      env: DJANGO=django==1.6.2
    - python: "2.6"
      env: DJANGO=django==1.6.6
    - python: "2.6"
      env: DJANGO=django==1.7
    - python: "2.6"
      env: DJANGO=django==1.8
    - python: "2.6"
      env: DJANGO=django==1.9



script:
  - bash test_runner.sh
